from typing import Iterator, TypedDict

class _Region(TypedDict):
    start: int
    end: int

class _CodonInfo(TypedDict):
    cds_pos: int
    codon_seq: str | None
    intra_codon: int | None
    codon_number: int | None
    initial_aa: str | None
    offset: int

class _CodingDistance(TypedDict):
    pos: int
    offset: int

class _Attributes:
    """ a lazy, dict-like view over a Transcript's GTF attributes """
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Transcript:
    def __init__(
        self,
        name: str | None = ...,
        chrom: str | None = ...,
        start: int = ...,
        end: int = ...,
        strand: str = ...,
        transcript_type: str = ...,
        exons: list[tuple[int, int]] | None = ...,
        cds: list[tuple[int, int]] | None = ...,
        sequence: str | None = ...,
        offset: int = ...,
        attributes: dict[str, str] | None = ...,
    ) -> None: ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __add__(self, other: Transcript | None) -> Transcript: ...
    def __radd__(self, other: Transcript | None) -> Transcript: ...

    @property
    def name(self) -> str:
        """transcript ID"""
        ...
    @property
    def chrom(self) -> str:
        """chromosome the gene is on"""
        ...
    @property
    def type(self) -> str:
        """transcript functional type (protein_coding etc.)"""
        ...
    @property
    def start(self) -> int:
        """transcript start position (TSS) on chromosome"""
        ...
    @property
    def end(self) -> int:
        """transcript end position on chromosome"""
        ...
    @property
    def strand(self) -> str:
        """strand the transcript is on (+ or -)"""
        ...
    @property
    def cds_start(self) -> int:
        """CDS start position on chromosome"""
        ...
    @property
    def cds_end(self) -> int:
        """CDS end position on chromosome"""
        ...

    @property
    def exons(self) -> list[_Region]:
        """list of exon coords as {'start': int, 'end': int} dicts"""
        ...
    @exons.setter
    def exons(self, exon_ranges: list[tuple[int, int]]) -> None: ...

    @property
    def cds(self) -> list[_Region]:
        """list of CDS coords as {'start': int, 'end': int} dicts"""
        ...
    @cds.setter
    def cds(self, cds_ranges: list[tuple[int, int]]) -> None: ...

    @property
    def cds_sequence(self) -> str: ...
    @cds_sequence.setter
    def cds_sequence(self, text: str) -> None: ...

    @property
    def genomic_offset(self) -> int:
        """distance the DNA sequence extends symmetrically beyond gene boundaries"""
        ...
    @genomic_offset.setter
    def genomic_offset(self, offset: int) -> None: ...

    @property
    def genomic_sequence(self) -> str: ...
    @genomic_sequence.setter
    def genomic_sequence(self, text: str) -> None: ...

    @property
    def attributes(self) -> _Attributes:
        """dict-like view of the raw key/value pairs from the GTF attributes field"""
        ...

    def in_exons(self, position: int) -> bool: ...
    def get_closest_exon(self, pos: int) -> _Region: ...
    def in_coding_region(self, pos: int) -> bool: ...
    def get_coding_distance(self, pos: int) -> _CodingDistance: ...
    def get_position_on_chrom(self, pos: int, offset: int = ...) -> int: ...
    def get_codon_number_for_cds_position(self, cds_pos: int) -> int: ...
    def get_position_within_codon(self, cds_pos: int) -> int: ...
    def reverse_complement(self, text: str) -> str: ...
    def get_centered_sequence(self, pos: int, length: int = ...) -> str: ...
    def get_codon_sequence(self, codon_num: int) -> str: ...
    def translate(self, text: str) -> str: ...
    def get_codon_info(self, pos: int) -> _CodonInfo: ...
    def get_boundary_distance(self, pos: int) -> int: ...
    def consequence(self, pos: int, ref: str, alt: str) -> str: ...
